stages:
  - build
  - test

before_script:
 - apt update --yes
 - apt install --yes cmake


build-gcc10:
  image: gcc:10
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ../
    - cmake --build .
  artifacts:
    untracked: true

build-gcc11:
  image: gcc:11
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ../
    - cmake --build .
  artifacts:
    untracked: true

test-gcc10:
  image: gcc:10
  stage: test
  needs: ["build-gcc10"]
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - sleep 60
    - echo "Code coverage is 90%"

test-gcc11:
  image: gcc:11
  stage: test
  needs: ["build-gcc11"]
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - sleep 60
    - echo "Code coverage is 90%"
