stages:
  - build
  - test

before_script:
 - apt update --yes
 - apt install --yes cmake
 - apt install --yes clang-format-11


build-gcc10:
  image: gcc:10
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ../
    - cmake --build .
  artifacts:
    untracked: true

build-gcc11:
  image: gcc:11
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ../
    - cmake --build .
  artifacts:
    untracked: true

test-gcc10:
  image: gcc:10
  stage: test
  needs: ["build-gcc10"]
  script:
    - find . -type d -name build -prune -o -iname "*.cpp" -print -o -iname "*.h" -print |xargs -I {} clang-format-11 -style=file --dry-run -Werror {}
    - cd build/tests
    - ./tests


test-gcc11:
  image: gcc:11
  stage: test
  needs: ["build-gcc11"]
  script:
    - find . -type d -name build -prune -o -iname "*.cpp" -print -o -iname "*.h" -print |xargs -I {} clang-format-11 -style=file --dry-run -Werror {}
    - cd build/tests
    - ./tests
